name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to destroy"
        required: true
        default: "dev"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_USE_OIDC: "true"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Plan
        id: tf-plan
        run: |
          EXIT_CODE=0
          terraform plan -destroy -detailed-exitcode -no-color -out tfplan || EXIT_CODE=$?
          echo "exitcode=$EXIT_CODE" >> "$GITHUB_OUTPUT"
          if [ "$EXIT_CODE" -eq 1 ]; then
            echo "Terraform Destroy Plan Failed!"
            exit 1
          fi

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan
          if-no-files-found: error
          retention-days: 7

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform

      - name: Terraform Destroy Apply
        run: terraform apply -auto-approve tfplan
