name: Deploy Static Web App

on:
    push:
        branches: [ main ]
        paths:
            - 'web/site/**'
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches: [ main ]
        paths:
            - 'web/site/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        working-directory: web/site
        run: |
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "web/site"     # path to app source
          output_location: "dist"      # Vite output
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_API_BASE_URL2: ${{ secrets.VITE_API_BASE_URL2 }}